version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
  albumservice:
    build: .
    volumes:
      - ./data/albumservice/images:/etc/images
    ports:
      - "8080:8080"
    depends_on:
      - mongo
