---
file:
  uploadDir: /etc/images
spring:
  data:
    mongodb.uri: mongodb://localhost/srini
    mongodb.authentication-database: srini
    mongo.repositories.enabled: true
---
file:
  uploadDir: /etc/test-images
spring:
  profiles: test
  data:
    mongodb.uri: mongodb://localhost/srini-test
    mongodb.authentication-database: srini-test
    mongo.repositories.enabled: true