---
spring:
  data:
    mongodb.uri: mongodb://localhost/srini
    mongodb.authentication-database: srini
    mongo.repositories.enabled: true
---
spring:
  profiles: test
  data:
    mongodb.uri: mongodb://localhost/srini
    mongodb.authentication-database: srini-test
    mongo.repositories.enabled: true